# .github/workflows/poll-recall.yml

name: Poll Recall.ai for Transcripts

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  poll:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.schedule == '*/5 * * * *' && env.ENABLE_GITHUB_WORKFLOWS == 'true'
    steps:
      - name: Call the polling endpoint
        run: curl --request GET --url "${{ secrets.POLLING_URL }}" --fail
